[package]
name = "sd-desktop-linux"
version = "0.1.0"
license = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }

[dependencies]
tokio = { workspace = true, features = ["fs"] }
libc =  { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
gl = "0.14"
gl-headless = "0.2"
# WARNING: gtk should follow the same version used by tauri
# https://github.com/tauri-apps/tauri/blob/tauri-v2.0.0-beta.17/core/tauri/Cargo.toml#L85C1-L85C51
gtk = { version = "0.18", features = [ "v3_24" ] }
