[package]
name = "sd-desktop-linux"
version = "0.1.0"
license = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }

[dependencies]
aho-corasick = "1.0.2"
atty = "0.2.14"
freedesktop_entry_parser = "1.3.0"
libc = "0.2.147"
mime = "0.3.17"
shlex = "1.1.0"
thiserror = "1.0.40"
xdg = "2.5.0"
xdg-mime = "0.3.3"

