name: Setup
description: Sets up runner, Rust and pnpm
inputs:
  token:
    description: Github token
    required: false
    default: ''
  save-cache:
    description: Whether to save the Rust cache
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: Install Rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal

    - name: Install pnpm
      uses: pnpm/action-setup@v2.2.2
      with:
        version: 7.x.x
        run_install: false

    - name: Cache LLVM and Clang
      if: runner.os == 'Windows'
      id: cache-llvm
      uses: actions/cache@v3
      with:
        path: C:/Program Files/LLVM
        key: llvm-15

    - name: Install LLVM and Clang
      if: runner.os == 'Windows'
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: '15'
        cached: ${{ steps.cache-llvm.outputs.cache-hit }}

    - name: Cache Rust deps
      uses: ./.github/actions/cache-rust-deps
      with:
        save-cache: ${{ inputs.save-cache }}

    - name: Run 'setup-system.sh' script
      shell: bash
      if: runner.os == 'Linux' || runner.os == 'macOS'
      run: ./.github/scripts/setup-system.sh

    - name: Run 'setup-system.ps1' script
      shell: powershell
      if: runner.os == 'Windows'
      run: ./.github/scripts/setup-system.ps1
      env:
        GITHUB_TOKEN: ${{ inputs.token }}

    - name: Generate Prisma client
      uses: ./.github/actions/generate-prisma-client
