[package]
name = "sd-media-metadata"
version = "0.0.0"
authors = ["Jake Robinson <jake@spacedrive.com>"]
edition = "2021"

[dependencies]
chrono = { workspace = true, features = ["serde"] }
image = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
specta = { workspace = true, features = ["chrono"] }
thiserror = { workspace = true }

kamadak-exif = "0.5.5"

# symphonia crate looks great for audio metadata
