[files]
extend-exclude = [
    ".git/",
    ".cspell/",
    ".github/actions/publish-artifacts/dist/",
    "interface/locales/",
]
ignore-hidden = false

[default]
extend-ignore-re = [
    "Lorem ipsum .*",
    "OS2GadFYJi0w8WbQ1KpUe",
]

[default.extend-words]
"udid" = "udid"

[default.extend-identifiers]
"Caf" = "Caf"
"unique_criterias" = "unique_criterias"
"passt" = "passt"
