[workspace]
resolver = "2"
members = [
  "core",
  "crates/*",
  # "crates/p2p/tunnel",
  # "crates/p2p/tunnel/utils",
  "apps/cli",
  "apps/desktop/src-tauri",
  "apps/desktop/crates/*",
  "apps/mobile/crates/*",
  "apps/server",
]

[workspace.dependencies]
prisma-client-rust =  { git = "https://github.com/Brendonovich/prisma-client-rust", tag = "0.6.8", features = [
  "rspc",
  "sqlite-create-many",
  "migrations",
  "sqlite",
], default-features = false }
prisma-client-rust-cli = { git = "https://github.com/Brendonovich/prisma-client-rust", tag = "0.6.8", features = [
  "rspc",
  "sqlite-create-many",
  "migrations",
  "sqlite",
], default-features = false }
prisma-client-rust-sdk = { git = "https://github.com/Brendonovich/prisma-client-rust", tag = "0.6.8", features = [
  "sqlite",
], default-features = false }

rspc = { version = "0.1.4" }
specta = { version = "1.0.3" }
httpz = { version = "0.0.3" }

swift-rs = { version = "1.0.1" }

tokio = { version = "1.25.0" }

[patch.crates-io]
# We use this patch so we can compile for the IOS simulator on M1
openssl-sys = { git = "https://github.com/spacedriveapp/rust-openssl", rev = "92c3dec225a9e984884d5b30a517e5d44a24d03b" }
# We patch this so that it can be built for IOS - The `main` branch uses macOS specific APIs
if-watch = { git = "https://github.com/oscartbeaumont/if-watch", rev = "410e8e1d2d0730f1441df1c29294fec4c3c04193" }

mdns-sd = { git = "https://github.com/oscartbeaumont/mdns-sd", rev = "45515a98e9e408c102871abaa5a9bff3bee0cbe8" } # TODO: Do upstream PR

rspc = { git = "https://github.com/oscartbeaumont/rspc", rev = "745f0b210f6d268a4cef5d43b595e88d99ac269f" }
httpz = { git = "https://github.com/oscartbeaumont/httpz", rev = "a5185f2ed2fdefeb2f582dce38a692a1bf76d1d6" }
