[workspace]
resolver = "2"
members = [
  "apps/desktop/src-tauri",
  "apps/mobile/rust",
  "core",
  "core/prisma",
  "apps/server",
]

[patch.crates-io]
# We use this patch so we can compile for the IOS simulator on M1
openssl-sys = { git = "https://github.com/spacedriveapp/rust-openssl" }
rspc = { git = "https://github.com/oscartbeaumont/rspc", rev = "1b2a299e9061c81ff90706923a6d2389ea7c107e" }

[patch."https://github.com/Brendonovich/prisma-client-rust.git"]
prisma-client-rust = { git = "https://github.com//Brendonovich/prisma-client-rust.git", rev = "82f71caf057c702dca48cd64f11ca8cc270a78e7", features = [
  "migrations",
  "rspc",
  "sqlite-create-many",
] }
prisma-client-rust-cli = { git = "https://github.com//Brendonovich/prisma-client-rust.git", rev = "82f71caf057c702dca48cd64f11ca8cc270a78e7", features = [
  "migrations",
  "rspc",
  "sqlite-create-many",
] }
