[workspace]
members = [
  "apps/desktop/src-tauri",
  "apps/mobile/rust",
  "core",
  "core/prisma",
  "apps/server",
]
resolver = "2"

[patch.crates-io]
# We use this patch so we can compile for the IOS simulator on M1
openssl-sys = { git = "https://github.com/spacedriveapp/rust-openssl" }

[patch."https://github.com/Brendonovich/prisma-client-rust.git"]
prisma-client-rust = { git = "https://github.com//Brendonovich/prisma-client-rust.git", rev = "fbfa3ecbbd35ca4b5a8e1f9948e7cabdc9c7e536" }
prisma-client-rust-cli = { git = "https://github.com//Brendonovich/prisma-client-rust.git", rev = "fbfa3ecbbd35ca4b5a8e1f9948e7cabdc9c7e536" }
