[package]
name = "sd-core-sync"
version = "0.0.0"
edition = "2021"

[features]
default = []

[dependencies]
# Spacedrive Sub-crates
sd-prisma = { path = "../../../crates/prisma" }
sd-sync = { path = "../../../crates/sync" }
sd-utils = { path = "../../../crates/utils" }
sd-actors = { path = "../../../crates/actors" }

# Workspace dependencies
prisma-client-rust = { workspace = true }
rmpv = { workspace = true }
rmp-serde = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
uhlc = { workspace = true }
uuid = { workspace = true }
