[package]
name = "sd-core-sync"
version = "0.0.0"
edition = "2021"

[features]
default = []

[dependencies]
# Spacedrive Sub-crates
sd-prisma = { path = "../../../crates/prisma" }
sd-sync = { path = "../../../crates/sync" }
sd-utils = { path = "../../../crates/utils" }
sd-actors = { path = "../../../crates/actors" }

# Workspace dependencies
async-channel = { workspace = true }
futures = { workspace = true }
futures-concurrency = { workspace = true }
prisma-client-rust = { workspace = true, features = ["rspc"] }
rmpv = { workspace = true }
rmp-serde = { workspace = true }
rspc = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
uhlc = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
tracing-test = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
