[package]
name    = "sd-mobile-core"
version = "0.1.0"

edition.workspace    = true
license.workspace    = true
repository.workspace = true
rust-version         = "1.64"

[dependencies]
# Spacedrive Sub-crates
sd-core = { path = "../../../../../core", features = ["mobile"], default-features = false }

# Workspace dependencies
futures    = { workspace = true }
once_cell  = { workspace = true }
rspc       = { workspace = true }
serde_json = { workspace = true }
tokio      = { workspace = true }
tracing    = { workspace = true }

# Specific Mobile Core dependencies
futures-channel = "0.3.30"
futures-locks   = "0.7.1"
