[package]
name    = "sd-mobile-core"
version = "0.1.0"

edition.workspace    = true
license.workspace    = true
repository.workspace = true
rust-version         = "1.64"

[target.'cfg(target_os = "android")'.dependencies]
sd-core = { default-features = false, features = ["mobile"], path = "../../../../../core" }

[target.'cfg(target_os = "ios")'.dependencies]
sd-core = { default-features = false, features = [
	"ffmpeg",
	"heif",
	"mobile"
], path = "../../../../../core" }

# Workspace dependencies
futures    = { workspace = true }
rspc       = { workspace = true }
serde_json = { workspace = true }
tokio      = { workspace = true }
tracing    = { workspace = true }

# Specific Mobile Core dependencies
futures-channel = "0.3.30"
futures-locks   = "0.7.1"
