[package]
name = "sd-p2p-tunnel"
version = "0.1.0"
authors = ["Oscar Beaumont <oscar@otbeaumont.me>"]
license.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
# Spacedrive Sub-crates
sd-p2p = { path = "../../" }
sd-p2p-proto = { path = "../proto" }

# Workspace dependencies
tokio = { workspace = true, features = ["io-util"] }
thiserror = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
