[package]
name = "sd-p2p-block"
version = "0.1.0"
authors = ["Oscar Beaumont <oscar@otbeaumont.me>"]
license.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
sd-p2p2 = { path = "../p2p2" }
sd-p2p-proto = { path = "../p2p-proto" }
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true
