[package]
name = "sd-fda"
version = "0.1.0"
authors = ["Jake Robinson <jake@spacedrive.com>"]
license = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }

[dependencies]
dirs = "5.0.1"
thiserror = "1.0.50"

[dev-dependencies]
tempfile = '3.8.1'
