name: Generate Prisma client
description: Generates the Prisma client, using a cached value if one is available
runs:
  using: 'composite'
  steps:
    - name: Cache Prisma codegen
      id: cache-prisma
      uses: actions/cache@v3
      with:
        path: ./core/src/prisma*.rs
        key: prisma-0-${{ runner.os }}-${{ hashFiles('./core/prisma/*', './Cargo.toml') }}

    - name: Generate Prisma client
      working-directory: core
      if: steps.cache-prisma.outputs.cache-hit != 'true'
      shell: bash
      run: cargo run -p prisma-cli --bin prisma --release -- generate
