[package]
name = "sd-server"
version = "0.1.0"
license = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }

[features]
assets = []

[dependencies]
sd-core = { path = "../../core", features = [
	"ffmpeg",
	"location-watcher",
	"heif",
] }
rspc = { workspace = true, features = ["axum"] }
axum = "0.6.20"
tokio = { workspace = true, features = ["sync", "rt-multi-thread", "signal"] }
tracing = { workspace = true }
http = "0.2.9"
include_dir = "0.7.3"
mime_guess = "2.0.4"
