[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
sd-core = { path = "../../core", features = ["ffmpeg"] }
rspc = { workspace = true, features = ["axum"] }
httpz = { workspace = true, features = ["axum"] }
axum = "0.6.17"
tokio = { workspace = true, features = ["sync", "rt-multi-thread", "signal"] }
tracing = "0.1.37"
ctrlc = "3.2.5"
http = "0.2.9"
hyper = "0.14.26"
