[package]
name = "sd-macos"
version = "0.1.0"
license = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }

[target.'cfg(target_os = "macos")'.dependencies]
swift-rs = { workspace = true }

[target.'cfg(target_os = "macos")'.build-dependencies]
swift-rs = { workspace = true, features = ["build"] }
