[package]
name = "sd-macos"
version = "0.1.0"
license.workspace = true
repository.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
swift-rs.workspace = true

[build-dependencies]
swift-rs = { workspace = true, features = ["build"] }
