[package]
name    = "sd-desktop"
version = "0.4.2"

authors              = ["Spacedrive Technology Inc <support@spacedrive.com>"]
default-run          = "sd-desktop"
description          = "The universal file manager."
edition.workspace    = true
license.workspace    = true
repository.workspace = true

[dependencies]
# Spacedrive Sub-crates
sd-core   = { path = "../../../core", features = ["ffmpeg", "heif"] }
sd-fda    = { path = "../../../crates/fda" }
sd-prisma = { path = "../../../crates/prisma" }

# Workspace dependencies
axum               = { workspace = true, features = ["headers", "query"] }
futures            = { workspace = true }
http               = { workspace = true }
hyper              = { workspace = true }
prisma-client-rust = { workspace = true }
rand               = { workspace = true }
rspc               = { workspace = true, features = ["tauri", "tracing"] }
serde              = { workspace = true }
serde_json         = { workspace = true }
specta             = { workspace = true }
strum              = { workspace = true, features = ["derive"] }
thiserror          = { workspace = true }
tokio              = { workspace = true, features = ["sync"] }
tracing            = { workspace = true }
uuid               = { workspace = true, features = ["serde"] }

# Specific Desktop dependencies
# WARNING: Do NOT enable default features, as that vendors dbus (see below)
opener               = { version = "0.7.1", features = ["reveal"], default-features = false }
specta-typescript    = "=0.0.7"
tauri-plugin-dialog  = "=2.0.0-rc.0"
tauri-plugin-os      = "=2.0.0-rc.0"
tauri-plugin-shell   = "=2.0.0-rc.0"
tauri-plugin-updater = "=2.0.0-rc.0"

# memory allocator
mimalloc = { workspace = true }

[dependencies.tauri]
features = ["linux-libxdo", "macos-private-api", "native-tls-vendored", "unstable"]
version  = "=2.0.0-rc.2"

[dependencies.tauri-specta]
features = ["derive", "typescript"]
git      = "https://github.com/spacedriveapp/tauri-specta"
rev      = "6069a05029"

[target.'cfg(target_os = "linux")'.dependencies]
# Spacedrive Sub-crates
sd-desktop-linux = { path = "../crates/linux" }

# Specific Desktop dependencies
# WARNING: dbus must NOT be vendored, as that breaks the app on Linux,X11,Nvidia
dbus = { version = "0.9.7", features = ["stdfd"] }
# https://github.com/tauri-apps/tauri/blob/tauri-v2.0.0-rc.2/core/tauri/Cargo.toml#L86
webkit2gtk = { version = "=2.0.1", features = ["v2_38"] }

[target.'cfg(target_os = "macos")'.dependencies]
# Spacedrive Sub-crates
sd-desktop-macos = { path = "../crates/macos" }

[target.'cfg(target_os = "windows")'.dependencies]
# Spacedrive Sub-crates
sd-desktop-windows = { path = "../crates/windows" }

[build-dependencies]
# Specific Desktop dependencies
tauri-build = "=2.0.0-rc.2"

[features]
ai-models       = ["sd-core/ai"]
custom-protocol = ["tauri/custom-protocol"]
default         = ["custom-protocol"]
devtools        = ["tauri/devtools"]
