[package]
name = "spacedrive"
version = "0.1.0"
description = "The next gen private virtual filesystem."
authors = ["Jamie Pine"]
license = ""
repository = "https://github.com/spacedriveapp/spacedrive"
default-run = "spacedrive"
edition = "2021"
build = "build.rs"

[build-dependencies]
tauri-build = { version = "1.0.0-rc.5", features = [] }

[dependencies]
# Project dependencies
tauri = { version = "1.0.0-rc.6", features = ["api-all", "macos-private-api"] }
sdcore = { path = "../../../core" }
# tauri-plugin-shadows = { git = "https://github.com/tauri-apps/tauri-plugin-shadows", features = ["tauri-impl"] }

# Universal Dependencies
tokio = { version = "1.17.0", features = ["sync"] }
window-shadows = "0.1.2"

# macOS system libs
[target.'cfg(target_os = "macos")'.dependencies]
cocoa = { git = "https://github.com/maxichrome/core-foundation-rs.git", branch = "add-window-utils" }
objc = "0.2.7"
swift-rs = { git = "https://github.com/Brendonovich/swift-rs.git", branch = "autorelease" }

[target.'cfg(target_os = "macos")'.build-dependencies]
swift-rs = { git = "https://github.com/Brendonovich/swift-rs.git", branch = "autorelease", features = ["build"] }

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
