[package]
name = "spacedrive"
version = "0.1.0"
description = "The universal file manager."
authors = ["Spacedrive Technology Inc."]
license = ""
repository = "https://github.com/spacedriveapp/spacedrive"
default-run = "spacedrive"
edition = "2021"

[dependencies]
tauri = { version = "1.2.4", features = ["api-all", "linux-protocol-headers", "macos-private-api", "updater"] }
rspc = { workspace = true, features = ["tauri"] }
httpz = { workspace = true, features = ["axum", "tauri"] } # TODO: The `axum` feature should be only enabled on Linux but this currently can't be done: https://github.com/rust-lang/cargo/issues/1197
sd-core = { path = "../../../core", features = ["ffmpeg", "location-watcher"] }
tokio = { workspace = true, features = ["sync"] }
window-shadows = "0.2.0"
tracing = "0.1.36"
serde = "1.0.145"
percent-encoding = "2.2.0"
http = "0.2.8"

[target.'cfg(target_os = "linux")'.dependencies]
axum = { version = "0.6.4", features = ["headers", "query"] }
rand = "0.8.5"

[target.'cfg(target_os = "macos")'.dependencies]
sd-desktop-macos.path = "../crates/macos"

[build-dependencies]
tauri-build = { version = "1.1.1", features = [] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
