[package]
name    = "sd-sync-example"
version = "0.1.0"

edition.workspace      = true
license.workspace      = true
publish                = false
repository.workspace   = true
rust-version.workspace = true

[dependencies]
# Spacedrive Sub-crates
sd-sync = { path = ".." }

# Workspace dependencies
axum               = { workspace = true }
http               = { workspace = true }
prisma-client-rust = { workspace = true }
rspc               = { workspace = true, features = ["axum"] }
serde              = { workspace = true, features = ["derive"] }
serde_json         = { workspace = true }
tokio              = { workspace = true, features = ["full"] }
uuid               = { workspace = true, features = ["v4"] }

# Specific Core dependencies
dotenv     = "0.15.0"
tower-http = { version = "0.4.4", features = ["cors"] } # Update blocked by http
