[package]
name = "sd-sync-example"
version = "0.1.0"
rust-version = "1.64"
publish = false
license = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }

[dependencies]
# Spacedrive Sub-crates
sd-sync = { path = ".." }

# Workspace dependencies
axum = { workspace = true }
http = { workspace = true }
prisma-client-rust = { workspace = true }
rspc = { workspace = true, features = ["axum"] }
serde_json = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["full"] }
uuid = { workspace = true, features = ["v4"] }

# Specific Core dependencies
dotenv = "0.15.0"
tower-http = { version = "0.4.4", features = ["cors"] } # Update blocked by http
