[package]
name = "sd-desktop-windows"
version = "0.1.0"
license = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }

[dependencies]
thiserror = "1.0.40"
normpath = "1.1.1"
libc = "0.2"

[dependencies.windows]
version = "0.48"
features = ["Win32_UI_Shell", "Win32_System_Com"]
