[package]
name = "sd-sync"
version = "0.1.0"
license.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
rand = "0.8.5"
specta = { workspace = true, features = ["uuid", "uhlc"] }
serde = "1.0.163"
serde_json = "1.0.96"
uhlc = "0.5.2"
uuid = { version = "1.3.3", features = ["serde", "v4"] }
prisma-client-rust = { workspace = true }
serde-value = "0.7.0"
