[package]
name = "sd-sync"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
specta = { workspace = true, features = ["uuid", "uhlc"] }
serde = "1.0.160"
serde_json = "1.0.96"
uhlc = "0.5.2"
uuid = { version = "1.3.1", features = ["serde", "v4"] }
prisma-client-rust = { workspace = true }
serde-value = "0.7.0"
