[package]
name = "sd-images"
version = "0.0.0"
authors = [
	"Jake Robinson <jake@spacedrive.com>",
	"Vítor Vasconcellos <vitor@spacedrive.com>",
]
license = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }

[features]
heif = ["dep:libheif-rs", "dep:libheif-sys"]

[dependencies]
image = "0.24.7"
webp = { version = "0.2.6", optional = true }
thiserror = "1.0.49"
resvg = "0.36.0"
rspc = { workspace = true, optional = true } # error conversion
specta = { workspace = true, optional = true }
serde = { workspace = true, optional = true, features = ["derive"] }
bincode = { version = "2.0.0-rc.3", features = [
	"derive",
	"alloc",
], optional = true }
once_cell = "1.18.0"
tracing = { workspace = true }

# both of these added *default* bindgen features in 0.22.0 and 2.0.0 respectively
# this broke builds as we build our own liibheif, so i disabled their default features
libheif-rs = { version = "0.22.0", default-features = false, optional = true }
libheif-sys = { version = "2.0.0", default-features = false, optional = true }
pdfium-render = { version = "0.8.8", features = ["image"] }
