[package]
name = "sdcore"
version = "0.1.0"
description = "A virtual distributed filesystem."
authors = ["Jamie Pine"]
license = "GNU GENERAL PUBLIC LICENSE"
repository = "https://github.com/jamiepine/spacedrive"
edition = "2021"

[dependencies]
swift-rs = "0.2.3"
hotwatch = "0.4.6"
hostname = "0.3.1"
# Universal Dependencies
anyhow = "1.0.44"
log = "0.4.14"
base64 = "0.13.0"
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4.0", features = ["serde"] }
serde_json = "1.0"
futures = "0.3"
data-encoding = "2.3.2"
ring = "0.17.0-alpha.10"
once_cell = "1.8.0"
int-enum = "0.4.0"
# Project dependencies
ts-rs = "6.1"
prisma-client-rust = { git = "https://github.com/Brendonovich/prisma-client-rust.git", tag = "0.4.0" }
walkdir = "^2.3.2"
libp2p = "0.43.0"
lazy_static = "1.4.0"
uuid = "0.8"
sysinfo = "0.23.9"
thiserror = "1.0.30"
core-derive = { path = "./derive" }

tokio = { version = "1.17.0", features = ["sync", "rt"] }
include_dir = {version = "0.7.2", features = ["glob"]}
async-trait = "0.1.52"
image = "0.24.1"
webp = "0.2.2"
uhlc = "0.4.1"
ffmpeg-next = "5.0.3"
