[package]
name = "sd-prisma"
version = "0.1.0"
edition = "2021"

[dependencies]
sd-cache = { path = "../cache" }
sd-sync = { path = "../sync" }

prisma-client-rust = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
