[package]
name = "sd-prisma"
version = "0.1.0"
edition = "2021"

[dependencies]
# Spacedrive Sub-crates
sd-sync = { path = "../sync" }

# Workspace dependencies
prisma-client-rust = { workspace = true }
rmpv = { workspace = true }
rmp-serde = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
