[package]
name = "sd-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
# Spacedrive Sub-crates
sd-prisma = { path = "../prisma" }

# Workspace dependencies
prisma-client-rust = { workspace = true }
rspc = { workspace = true, features = ["unstable"] }
thiserror = { workspace = true }
uuid = { workspace = true }
