[package]
name = "sd-core-cloud-sync"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64.workspace = true
chrono.workspace = true
sd-cloud-api = { path = "../../../crates/cloud-api" }
sd-core-sync = { path = "../sync" }
sd-prisma = { path = "../../../crates/prisma" }
sd-sync = { path = "../../../crates/sync" }
sd-utils = { path = "../../../crates/utils" }
serde.workspace = true
serde_json = "1.0.113"
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true
prisma-client-rust = { workspace = true }
