[package]
name = "sd-file-ext"
version = "0.0.0"
edition = "2021"
authors = [
    "Brendan Allen <brendan@spacedrive.com>",
    "Jamie Pine <jamie@spacedrive.com>",
]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
int-enum = "0.5.0"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.85"
strum = { version = "0.24", features = ["derive"] }
strum_macros = "0.24"
tokio = { workspace = true, features = ["fs", "rt", "io-util"] }

[dev-dependencies]
tokio = { workspace = true, features = ["fs", "rt", "macros"] }
