[package]
name = "sd-cloud-api"
version = "0.1.0"
license.workspace = true
edition.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.22"
serde.workspace = true
serde_json.workspace = true
thiserror = "1.0.50"
uuid.workspace = true
rspc = { workspace = true }
specta.workspace = true
