[package]
name = "sd-p2p-tunnel"
version = "0.1.0"
authors = ["Oscar Beaumont <oscar@otbeaumont.me>"]
license.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
sd-p2p2 = { path = "../p2p2" }
tokio = { workspace = true, features = ["io-util"] }
