[package]
name = "sd-sync-generator"
version = "0.1.0"
license = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }

[dependencies]
prisma-client-rust-sdk = { workspace = true }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }

nom = "7.1.3"
