[package]
name = "sd-sync-generator"
version = "0.1.0"
license = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }

[dependencies]
nom = "7.1.3"
once_cell = "1.18.0"
prisma-client-rust-sdk = { workspace = true }
proc-macro2 = "1.0.66"
quote = "1.0.33"
serde = { version = "1.0.188", features = ["derive"] }
thiserror = "1.0.48"
