[package]
name = "sd-sync-generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.3"
once_cell = "1.17.1"
prisma-client-rust-sdk = { workspace = true }
proc-macro2 = "1.0.56"
quote = "1.0.26"
serde = { version = "1.0.160", features = ["derive"] }
thiserror = "1.0.40"
