[package]
name = "sd-desktop-macos"
version = "0.1.0"
license = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }

[dependencies]
swift-rs = { workspace = true, features = ["serde"] }
serde = { version = "1.0" }

[build-dependencies]
swift-rs = { workspace = true, features = ["build"] }
