[package]
name = "sd-desktop-macos"
version = "0.1.0"
license = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }

[dependencies]
serde = { version = "1.0" }

[target.'cfg(target_os = "macos")'.dependencies]
swift-rs = { workspace = true, features = ["serde"] }

[target.'cfg(target_os = "macos")'.build-dependencies]
swift-rs = { workspace = true, features = ["build"] }
