[package]
name = "sd-mobile-android"
version = "0.1.0"
rust-version = "1.64.0"
license = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }

[lib]
# Android can use dynamic linking since all FFI is done via JNI
crate-type = ["cdylib"]

[target.'cfg(target_os = "android")'.dependencies]
# FFI
jni = "0.19.0"

# Core mobile handling stuff
sd-mobile-core = { path = "../core" }

# Other
tracing = { workspace = true }
