[package]
name = "sd-cli"
version = "0.1.0"
license = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }

[dependencies]
sd-crypto = { path = "../../crates/crypto" }

anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
hex = { workspace = true }
tokio = { workspace = true, features = ["io-util", "rt-multi-thread"] }

indoc = "2.0.4"
