[package]
name = "sd-p2p"
version = "0.1.0"
description = "Rust Peer to Peer Networking Library"
authors = ["Oscar Beaumont <oscar@otbeaumont.me>"]
license.workspace = true
repository.workspace = true
edition.workspace = true

[features]
default = []
serde = []
specta = []

[dependencies]
tokio = { workspace = true, features = [
	"macros",
	"sync",
	"time",
	"io-util",
	"fs",
] }
libp2p = { version = "0.51.0", features = ["tokio", "quic", "serde"] }
mdns-sd = "0.6.1"
thiserror = "1.0.39"
tracing = "0.1.37"
serde = { version = "1.0.152", features = ["derive"] }
rmp-serde = "1.1.1"
specta = { workspace = true }
flume = "0.10.14"
tokio-util = { version = "0.7.7", features = ["compat"] }
arc-swap = "1.6.0"

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread"] }
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
