[package]
name = "sd-p2p"
version = "0.1.0"
edition = "2021"

[dependencies]
sd-tunnel-utils = { path = "./tunnel/utils" }

dashmap = "5.3.4"
rcgen = "0.9.2"
rustls = "0.20.6"
tokio = { workspace = true, features = ["macros", "sync"] }
if-watch = "1.1.1"
thiserror = "1.0.31"
mdns-sd = "0.5.5"
quinn = "0.8.3"
futures-util = "0.3.21"
ts-rs = "6.2.0"
serde = { version = "1.0.138", features = ["derive"] }
bip39 = { version = "1.0.1", features = ["rand"] }
rmp-serde = "1.1.0"
spake2 = "0.3.1"
ctrlc = { version = "3.2.2", features = ["termination"] }
tracing = "0.1.35"
specta = "0.0.2"

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread"] }
