name: Setup System and Rust
description: Setup System and Rust
inputs:
  token:
    description: Github token
    required: false
    default: ''
  target:
    description: toolchain target triple
    required: false
  setup-arg:
    description: Argument for the system setup script
    required: false
    default: ''
  save-cache:
    description: Whether to save the System cache
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: Restore cached LLVM and Clang
      if: ${{ runner.os == 'Windows' }}
      id: cache-llvm-restore
      uses: actions/cache/restore@v3
      with:
        key: llvm-15
        path: C:/Program Files/LLVM

    - name: Install LLVM and Clang
      if: ${{ runner.os == 'Windows' }}
      uses: KyleMayes/install-llvm-action@v1
      with:
        cached: ${{ steps.cache-llvm-restore.outputs.cache-hit }}
        version: '15'

    - name: Save LLVM and Clang
      if: ${{ runner.os == 'Windows' && inputs.save-cache == 'true' }}
      id: cache-llvm-save
      uses: actions/cache/save@v3
      with:
        key: ${{ steps.cache-llvm-restore.outputs.cache-primary-key }}
        path: C:/Program Files/LLVM

    - name: Install Nasm
      if: ${{ runner.os != 'Linux' }}
      uses: ilammy/setup-nasm@v1

    - name: Setup Rust and Dependencies
      uses: ./.github/actions/setup-rust
      with:
        target: ${{ inputs.target }}
        save-cache: ${{ inputs.save-cache }}

    - name: Run setup.sh script
      shell: bash
      if: ${{ runner.os == 'Linux' || runner.os == 'macOS' }}
      run: ./scripts/setup.sh ${{ inputs.setup-arg }}

    - name: Run setup.ps1 script
      shell: powershell
      if: ${{ runner.os == 'Windows' }}
      run: ./scripts/setup.ps1

    - name: Setup shared libraries
      shell: bash
      env:
        TARGET_TRIPLE: ${{ inputs.target }}
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        pushd scripts
        npm i --production
        popd
        node scripts/preprep.mjs
