[package]
name = "sdcore-lib"
version = "0.1.0"
edition = "2021"

[features]
default = []
ios = ["objc", "objc_id"]
android = ["jni"]

[lib]
name = "sdcore"
crate-type = ["staticlib", "cdylib"] # staticlib for IOS and cdylib for Android

[dependencies]
once_cell = "1.13.0"
sdcore = { path = "../../../core", features = ["mobile", "p2p"], default-features = false }
serde_json = "1.0.83"
tokio = "1.20.1"
openssl = { version = "0.10.41", features = ["vendored"] } # Override features of transitive dependencies
objc = { version = "0.2.7", optional = true }
objc_id = { version = "0.1.1", optional = true }
jni = { version = "0.19.0", optional = true }
