name: Setup Node.js, pnpm and dependencies
description: Setup Node.js, pnpm and dependencies
inputs:
  token:
    description: Github token
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8.x.x

    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        token: ${{ inputs.token }}
        node-version: 18
        check-latest: true

    - name: Install pnpm deps
      shell: ${{ runner.os == 'Windows' && 'powershell' || 'bash' }}
      run: pnpm i --frozen-lockfile
