name: CI

on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - '**/.md'
  workflow_dispatch:

env:
  CARGO_INCREMENTAL: 1
  # CARGO_LOG: cargo::core::compiler::fingerprint=trace
  CUSTOM_APT_FLAGS: --no-install-recommends

jobs:
  typescript:
    name: TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 17

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
      
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      
      - name: Install pnpm dependencies
        run: pnpm --frozen-lockfile i

      - name: Perform typechecks
        run: pnpm typecheck

  build-core:
    name: Build Core (${{ matrix.platform }})
    runs-on: ${{ matrix.platform }}
    needs: typescript
    strategy:
      fail-fast: true
      matrix:
        platform: [ubuntu-latest, macos-latest] # TODO: Windows: , windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 17

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 7
          run_install: false
      
      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rustfmt, rust-src
      
      - name: Cache Rust Dependencies
        uses: Swatinem/rust-cache@v1
        with:
          sharedKey: core-v1-${{ hashFiles('**/Cargo.lock') }}

      - name: Run 'setup-system.sh' script
        if: matrix.platform == 'ubuntu-latest' || matrix.platform == 'macos-latest'
        run: ./.github/scripts/setup-system.sh

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install pnpm dependencies
        run: pnpm --frozen-lockfile i
      
      - name: Cache Prisma codegen
        id: cache-prisma
        uses: actions/cache@v3
        with:
          path: ./core/src/prisma.rs
          key: prisma-${{ hashFiles('./core/prisma/Cargo.toml', './core/prisma/schema.prisma', './core/prisma/src/main.rs') }}

      - name: Generate Prisma client
        working-directory: core
        if: steps.cache-prisma.outputs.cache-hit != 'true'
        run: cargo run --frozen --locked -p prisma-cli --release -- generate

      - name: Check Core
        run: cargo check --frozen --locked -p sdcore --release

      - name: Check Server
        run: cargo check --frozen --locked -p server --release

      - name: Build Core
        run: cargo build --frozen --locked -p sdcore --release

      - name: Build Server
        run: cargo build --frozen --locked -p server --release

      - name: Build Server (x2)
        run: cargo build --frozen --locked -p server --release

      - name: Bundle Desktop
        run: pnpm desktop tauri build -v
      
      - name: Bundle Desktop (x2)
        run: pnpm desktop tauri build -v

      # TODO: If ubuntu and on main branch publish new docker image for server

      - name: Publish artifacts
        uses: ./.github/actions/publish-desktop-artifacts
