name: CI
on:
  pull_request:
  push:
    branches:
    - main
    - ci
  workflow_dispatch:

jobs:
  test-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    
    # Optimisation for windows
    - name: Rename existing rust toolchain (Windows)
      if: matrix.os == 'windows-latest'
      run: Rename-Item C:\Users\runneradmin\.rustup\toolchains\stable-x86_64-pc-windows-msvc C:\Users\runneradmin\.rustup\toolchains\stable-x86_64-pc-windows-msvc.old
    
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 16
        
    - name: Install Rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
        components: rustfmt, rust-src
    
    - name: Cache Rust Dependencies
      uses: Swatinem/rust-cache@ce325b60658c1b38465c06cc965b79baf32c1e72
        
    - name: Cache pnpm dependencies
      uses: actions/cache@v2
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-

    - name: Install pnpm
      uses: pnpm/action-setup@v2.2.1
      with:
        version: 6.32.6
    
    - name: Install dependencies (Ubuntu)
      if: matrix.platform == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends
          libgtk-3-dev \
          webkit2gtk-4.0 \
          libappindicator3-dev \
          librsvg2-dev \
          patchelf \
          libssl-dev \
          libavcodec-dev \
          libavdevice-dev \
          libavfilter-dev \
          libavformat-dev \
          libavresample-dev \
          libavutil-dev \
          libswscale-dev \
          libswresample-dev \
          pkg-config \
          ffmpeg
    
    - name: Install dependencies (macOS)
      if: matrix.platform == 'macos-latest'
      run: |
        brew install ffmpeg
        
    - name: Install pnpm dependencies
      run: pnpm i
      
    - name: Build codegen
      run: pnpm prep:ci
      
    - name: Build frontend
      run: pnpm desktop build
      
    - name: Build Tauri app 
      uses: tauri-apps/tauri-action@v0
      with:
        projectPath: apps/desktop
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}