name: Rust Clippy check

on:
  pull_request:
  push:
    paths:
      - '**.rs'
  workflow_dispatch:

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - run: rustup component add clippy
      
      - name: Install Dependencies
      - run: sudo apt update && sudo apt install libdbus-1-dev pkg-config
      
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
