name: Build ffmpeg

on:
  push:
    paths:
      - '.github/workflows/ffmpeg.yml'
      - '.github/scripts/ffmpeg/**'
    branches:
      - main
  pull_request:
    paths:
      - '.github/workflows/ffmpeg.yml'
      - '.github/scripts/ffmpeg/**'
  workflow_dispatch:

# Cancel previous runs of the same workflow on the same branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FFMPEG_VERSION: '6.0'

jobs:
  build-ffmpeg:
    strategy:
      matrix:
        settings:
          # - target: x86_64-macos-none
          # - target: aarch64-macos-none
          - target: x86_64-windows-gnu
          - target: aarch64-windows-gnu
          - target: x86_64-linux-gnu
          - target: aarch64-linux-gnu
          # - target: x86-linux-musl
          # - target: aarch64-linux-musl
    name: Build ffmpeg ${{ matrix.settings.target }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
          platforms: linux/amd64
          driver-opts: |
            image=moby/buildkit:master
            network=host

      - name: Build ffmpeg
        run: |
          set -euxo pipefail
          cd .github/scripts/ffmpeg
          docker build --no-cache --build-arg TARGET=${{ matrix.settings.target }} -o . .

      - name: Publish ffmpeg
        uses: actions/upload-artifact@v3
        with:
          name: ffmpeg-6.0-${{ matrix.settings.target }}
          path: .github/scripts/ffmpeg/out/*
          if-no-files-found: error
