name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

# NOTE: For Linux builds, we can only build with Ubuntu. It should be the oldest base system we intend to support. See PR-759 & https://tauri.app/v1/guides/building/linux for reference.

jobs:
  desktop-main:
    name: Desktop - Main (${{ matrix.platform }})
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Install pnpm dependencies
        run: pnpm i --frozen-lockfile

      - name: Apply build patches
        run: pnpm desktop build

      - name: Build
        uses: tauri-apps/tauri-action@dev
        env:
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          projectPath: apps/desktop

      - name: Publish Artifacts
        uses: ./.github/actions/publish-artifacts
        with:
          profile: release
